### ISSUE TITLE
Codegens

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-auth#10]
https://www.graphql-code-generator.com/docs/plugins/typescript-graphql-request

```js
import { GraphQLClient } from "graphql-request";
import { getSdk } from "./__generated__/graphql-request";

const client = new GraphQLClient(process.env.GRAPHQL_ENDPOINT, {
  headers: {
    "x-hasura-admin-secret": process.env.GRAPHQL_ADMIN_SECRET,
  },
});
export const gqlSDK = getSdk(client);
```

```yaml
overwrite: true
schema: "http://localhost:8080/v1/graphql"
headers:
  x-hasura-admin-secret: hello123
documents: "nhost/utils/**/*.graphql"
generates:
  nhost/utils/__generated__/graphql-request.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
```

```
     // package.json scripts:
    "codegen": "graphql-codegen --config codegen.yaml"
```
