### ISSUE TITLE
Migrations on fresh instance broken

### ISSUE THREAD

**Issue by MichalNemec** [nhost/hasura-auth#182]
```
version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
      - ./docker/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.7.0
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    ports:
      - '8080:8080'
  hasura-auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - postgres
      - graphql-engine
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      AUTH_SMTP_HOST: mailhog
      AUTH_SMTP_PORT: 1025
    ports:
      - '4000:4000'
    volumes:
      - ./email-templates:/app/email-templates
  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_PASS: ${AUTH_SMTP_PASS}
      SMTP_USER: ${AUTH_SMTP_USER}
      SMTP_SECURE: '${AUTH_SMTP_SECURE}'
      SMTP_SENDER: ${AUTH_SMTP_SENDER}
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    volumes:
      - ./docker/data/mailhog:/maildir

```

Taken from here including `.env` file, NOTHING was changed.

output from docker:
```
> hasura-auth@0.8.1 start /app

> node ./dist/start.js


{"level":30,"time":1654105997406,"pid":19,"hostname":"1e7e70946518","msg":"Log level: info"}

{"level":30,"time":1654105998252,"pid":19,"hostname":"1e7e70946518","msg":"Waiting for Hasura to be ready..."}

{"level":30,"time":1654105998263,"pid":19,"hostname":"1e7e70946518","msg":"Hasura is ready"}

{"level":30,"time":1654105998263,"pid":19,"hostname":"1e7e70946518","msg":"Applying migrations..."}

(node:19) UnhandledPromiseRejectionWarning: Error: Migration failed. Reason: An error occurred running 'create-migrations-table'. Rolled back this migration. No further migrations were run. Reason: schema "auth" does not exist

    at applyMigrations (/app/dist/migrations.js:62:19)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async start (/app/dist/server.js:43:5)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
