### ISSUE TITLE
Auth_refresh_token permissions for new role are deleted at nhost up

### ISSUE THREAD

**Issue by juicygoose** [nhost/hasura-auth#406]
Hi,

I have created a new role called `readOnlyClient` and given the following permissions to this role:
```
select_permissions:
  - role: readOnlyClient
    permission:
      columns:
        - id
        - metadata
        - user_id
      filter: {}
```
in the file `auth_refresh_tokens.yaml`

Every time I boot my application, the permission is erased and I have the following git diff :
![image](https://github.com/nhost/hasura-auth/assets/15606243/3d1d70a4-ef32-4680-a637-5bfc736351d2)

Would it be possible to have a look as it is impacting some of the features used in my application ?

Many thanks in advance,
Alex
