### ISSUE TITLE
custom claims not working with JSONata array syntax

### ISSUE THREAD

**Issue by xmlking** [nhost/hasura-auth#434]
I am using custom claims / AUTH_JWT_CUSTOM_CLAIMS
As per [this](https://github.com/nhost/hasura-auth/blob/main/docs/recipes/custom-hasura-claims.md?plain=1) document, [JSONata](https://jsonata.org/) syntax should be supported. 

 
## This is Working

```toml
[[auth.session.accessToken.customClaims]]
key = 'org-id'
value = 'organizations[].organization'
```
```json
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-org-id": "{\"chinthagunta\",\"example\"}",
    "x-hasura-allowed-roles": [
      "me",
      "user",
      "manager"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "d3b12728-accf-4732-83ac-2e605341731c",
    "x-hasura-user-is-anonymous": "false"
  },
  "sub": "d3b12728-accf-4732-83ac-2e605341731c",
  "iat": 1699434443,
  "exp": 1699435343,
  "iss": "hasura-auth"
}
```

## This is NOT Working

```toml
[[auth.session.accessToken.customClaims]]
key = 'org-id'
value = 'organizations[0].organization'
```
```json
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "me",
      "user",
      "manager"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "d3b12728-accf-4732-83ac-2e605341731c",
    "x-hasura-user-is-anonymous": "false"
  },
  "sub": "d3b12728-accf-4732-83ac-2e605341731c",
  "iat": 1699434606,
  "exp": 1699435506,
  "iss": "hasura-auth"
}
```

hasura-auth logs
```logs
nhost-kit-auth-1  | {"level":"warn","message":"Invalid custom JWT GraphQL Query","request":"query ($userId: uuid!) { user (id: $userId) { organizations[0] { organization } } }"}
nhost-kit-auth-1  | {"level":"warn","message":"Invalid custom JWT GraphQL Query","request":"query ($userId: uuid!) { user (id: $userId) { organizations[0] { organization } } }"}
nhost-kit-auth-1  | {"level":"warn","message":"Invalid custom JWT GraphQL Query","request":"query ($userId: uuid!) { user (id: $userId) { organizations[0] { organization } } }
```
