### ISSUE TITLE
Auth server need custom CA certs when working behind company proxies 

### ISSUE THREAD

**Issue by xmlking** [nhost/hasura-auth#552]
## Problem 
**Auth** server cannot communicate to **oauth** providers when running on laptop behind corp proxy environment with `nhost up` cli command. 

## Context
In many corporate environments all network traffic from laptops has to go through proxies (running on-device/central) which act as `man-in-the-middle` for `https` traffic.  Due to TLS handshake failure between `auth` server and oauth providers like `azure`, we are getting error. Same code works when running outside corp proxy environment.   

# Workaround
We need to add proxy's CA Cert to container's system trusted certifications to make tls handshake work between `auth` server and `azure` .
 
workaround is, create `compose.override.yml` file with following overlay options in repo root, then copy `.nhost/docker-compose.yaml` file generated by `nhost up`  to root, then run `docker compose up` to use both files. 

```yaml

services:
  ###########################################################################
  # hasura auth
  ###########################################################################
  auth:
    volumes:
      - ./cacerts/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
  ###########################################################################
  # hasura storage
  ###########################################################################
  storage:
    volumes:
      - ./cacerts/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
```

Even though this works, it hiders the developer productivity of `nhsot` cli 

## Ask
Please provide a way to extend generated docker compose file to include extra volume mounting option so we can use custom CA certs with `auth` and `storage` services. 
Options:
1. Auto detect user supplied `compose.override.yml` [overlay](https://docs.docker.com/compose/multiple-compose-files/merge/) file in root and use both files. 
2. Provide options to mount custom volume for `auth` and `storage` containers  in `nhost.toml`
