### ISSUE TITLE
SMTP method not applied from nhost.toml 

### ISSUE THREAD

**Issue by xmlking** [nhost/hasura-auth#558]
I am setting SMTP method = 'PLAIN' but still seeing `SMTP auth LOGIN method is deprecated, using PLAIN instead` messages in **auth** server logs, after I started with `nhost up` 

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/1de4eb37-2fa3-449b-b9f2-1619f3e8ec7f">

nhost.toml

```toml
[provider]
[provider.smtp]
user = '{{ secrets.AUTH_SMTP_USER }}'
password = '{{ secrets.AUTH_SMTP_PASS }}'
sender = '{{ secrets.AUTH_SMTP_SENDER }}'
host = '{{ secrets.AUTH_SMTP_HOST }}'
port = 1025
secure = false
method = 'PLAIN'
```

generated docker compose file
<img width="669" alt="image" src="https://github.com/user-attachments/assets/559d980c-13c0-41ac-9578-d7769bcf7567">
