### ISSUE TITLE
customClaims provide option for default value

### ISSUE THREAD

**Issue by xmlking** [nhost/hasura-auth#610]
I am using customClaims where for some cases this session variable might be **null**. 
when I have permissions setup with `{"org_id":{"_eq":"x-hasura-default-org"}}`, when x-hasura-default-org is null, I will get `invalid input syntax for type uuid: \"null\"` error 

```toml
[[auth.session.accessToken.customClaims]]
key = 'default-org'
value = 'defaultOrg'
```

<img width="1507" alt="Image" src="https://github.com/user-attachments/assets/02766887-9b89-4c7c-a966-555d645edea7" />

## Ask

as suggested in this hasura issue, provide option to set default value for `customClaims`  e.g.

```toml
[[auth.session.accessToken.customClaims]]
key = 'default-org'
value = 'defaultOrg'
defalt = '00000000-0000-0000-0000-000000000000'
```

https://github.com/hasura/graphql-engine/issues/5134
