### ISSUE TITLE
'user' and 'me' roles not added when use allowedRoles

### ISSUE THREAD

**Issue by st3phan** [nhost/hasura-auth#62]
Given I have the following set in `nhost/config.yaml`:

```yml
user:
    allowed_roles: user,me,company,freelancer
    default_allowed_roles: user,me,company,freelancer
```

When I then do a `signUp` I expect the `user` and `me` roles to be added the to user by default even if I did not add them to the `allowedRoles` option.

```js
nhost.auth.signUp({
  email,
  password,
  options: {
    displayName: name,
    defaultRole: 'freelancer',
    allowedRoles: ['freelancer'],
  },
});
```
